# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190216_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
