# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='otp',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
