# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='courierid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
