# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-01 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receivedOrder',
        ),
    ]
